spring.application.name=RealTimeCaption

#vosk.model.path=model/vosk-model-small-cn-0.22
vosk.model.path=model/vosk-model-cn-0.22
# (??) ?? Python Whisper ??? API ??
#whisper.api.url=http://localhost:5001/transcribe

# (??) ???? C++ Whisper ???? API ???
# ??????IP??????? whisper.cpp server ?????????
# ????? C++ ???????? 8081 ???
whisper.api.url=http://localhost:8081/inference

